version: '3'

services:

  coderstore-almeida:
    build:
      context: .
    container_name: coderstore-almeida
    restart: always
    networks:
      - proxy_default

networks:
  proxy_default:
    external: true
